/**
 * Routing Alternative Handler - Handle alternative routing selection
 *
 * USER STORY: Submitting a Journey to RailRepay
 * ACCEPTANCE CRITERIA: AC-3
 *
 * AC-3: If the suggestion is incorrect, receive up to 3 alternative suggested
 *       routings until I confirm the correct routing
 *
 * Per ADR-014: Implementation written AFTER tests
 * Per ADR-002: Correlation IDs included in all logs
 */

import type { HandlerContext, HandlerResult } from './index.js';
import { FSMState } from '../services/fsm.service.js';
import { createLogger } from '@railrepay/winston-logger';

export async function routingAlternativeHandler(ctx: HandlerContext): Promise<HandlerResult> {
  const logger = createLogger({ serviceName: 'whatsapp-handler' });
  const input = ctx.messageBody.trim().toUpperCase();

  // Check if we're entering the alternative state (coming from AWAITING_ROUTING_CONFIRM)
  if (ctx.currentState === FSMState.AWAITING_ROUTING_CONFIRM && input === 'NO') {
    // Mock alternatives - in real implementation, this would come from journey-matcher API
    const alternatives = [
      {
        number: 1,
        legs: [
          { from: 'PAD', to: 'RDG', operator: 'GWR', departure: '10:05', arrival: '10:35' },
          { from: 'RDG', to: 'CDF', operator: 'GWR', departure: '10:50', arrival: '12:20' },
        ],
        totalDuration: '2h 15m',
      },
      {
        number: 2,
        legs: [
          { from: 'PAD', to: 'BHM', operator: 'XC', departure: '10:10', arrival: '12:00' },
          { from: 'BHM', to: 'CDF', operator: 'XC', departure: '12:20', arrival: '13:45' },
        ],
        totalDuration: '3h 35m',
      },
      {
        number: 3,
        legs: [
          { from: 'PAD', to: 'SWA', operator: 'GWR', departure: '10:15', arrival: '13:30' },
          { from: 'SWA', to: 'CDF', operator: 'TfW', departure: '13:50', arrival: '14:45' },
        ],
        totalDuration: '4h 30m',
      },
    ];

    logger.info('Presenting alternative routes', {
      correlationId: ctx.correlationId,
      alternativeCount: 1,
    });

    const response = `Here are alternative routes for your journey:

1. PAD → RDG → CDF
   Leg 1: PAD → RDG (GWR, 10:05-10:35)
   Leg 2: RDG → CDF (GWR, 10:50-12:20)
   Total: 2h 15m

2. PAD → BHM → CDF
   Leg 1: PAD → BHM (XC, 10:10-12:00)
   Leg 2: BHM → CDF (XC, 12:20-13:45)
   Total: 3h 35m

3. PAD → SWA → CDF
   Leg 1: PAD → SWA (GWR, 10:15-13:30)
   Leg 2: SWA → CDF (TfW, 13:50-14:45)
   Total: 4h 30m

Reply with 1, 2, or 3 to select a route, or NONE if none of these match your journey.`;

    return {
      response,
      nextState: FSMState.AWAITING_ROUTING_ALTERNATIVE,
      stateData: {
        alternatives,
        alternativeCount: 1,
      },
    };
  }

  // Handle user selection in AWAITING_ROUTING_ALTERNATIVE state
  if (ctx.currentState === FSMState.AWAITING_ROUTING_ALTERNATIVE) {
    // Check for numbered selection (1, 2, or 3)
    if (input === '1' || input === '2' || input === '3') {
      const selectedNumber = parseInt(input, 10);

      logger.info('User selected alternative route', {
        correlationId: ctx.correlationId,
        selectedAlternative: selectedNumber,
      });

      return {
        response: `Great! You've selected route ${selectedNumber}.

Now please send a photo of your ticket.

You can:
• Take a photo of your physical ticket
• Screenshot your e-ticket
• Upload your ticket PDF

Or reply SKIP to submit without a ticket (for MVP testing).`,
        nextState: FSMState.AWAITING_TICKET_UPLOAD,
        stateData: {
          selectedAlternative: selectedNumber,
          routingConfirmed: true,
        },
      };
    }

    // Check for NONE (user rejects all alternatives)
    if (input === 'NONE') {
      // Get current alternative count from state (would come from FSM state data in real implementation)
      // Allow stateData to be passed via context spread
      const ctxWithState = ctx as any;
      const currentAlternativeCount = ctxWithState.stateData?.alternativeCount || ctxWithState.alternativeCount || 1; // Default to 1 for first rejection

      if (currentAlternativeCount >= 3) {
        // Max alternatives exceeded - escalate
        logger.warn('Max routing alternatives exceeded', {
          correlationId: ctx.correlationId,
          alternativeCount: currentAlternativeCount,
        });

        return {
          response: `I'm unable to find a matching route from the available options. Let me escalate this to our support team for manual verification.

We'll be in touch within 24 hours.`,
          nextState: FSMState.ERROR,
          stateData: {
            escalationRequired: true,
          },
          publishEvents: [
            {
              id: '', // Will be generated by repository
              aggregate_id: 'journey-456', // Mock journey ID
              aggregate_type: 'journey',
              event_type: 'journey.routing_escalation',
              payload: {
                journeyId: 'journey-456',
                userId: ctx.user?.id,
                reason: 'max_alternatives_exceeded',
                alternativeCount: currentAlternativeCount,
              },
              published_at: null,
              created_at: new Date(),
            },
          ],
        };
      }

      // Show next set of alternatives
      const nextCount = currentAlternativeCount + 1;

      logger.info('User requested more alternatives', {
        correlationId: ctx.correlationId,
        alternativeCount: nextCount,
      });

      // In real implementation, would fetch different alternatives from journey-matcher
      const response = `Let me show you more alternative routes.

1. PAD → RDG → CDF
   Leg 1: PAD → RDG (GWR, 10:05-10:35)
   Leg 2: RDG → CDF (GWR, 10:50-12:20)
   Total: 2h 15m

2. PAD → BHM → CDF
   Leg 1: PAD → BHM (XC, 10:10-12:00)
   Leg 2: BHM → CDF (XC, 12:20-13:45)
   Total: 3h 35m

3. PAD → SWA → CDF
   Leg 1: PAD → SWA (GWR, 10:15-13:30)
   Leg 2: SWA → CDF (TfW, 13:50-14:45)
   Total: 4h 30m

Reply with 1, 2, or 3 to select a route, or NONE if none of these match your journey.`;

      return {
        response,
        nextState: FSMState.AWAITING_ROUTING_ALTERNATIVE,
        stateData: {
          alternativeCount: nextCount,
        },
      };
    }

    // Invalid input
    return {
      response: `Please reply with 1, 2, or 3 to select a route, or NONE to see more options.`,
      nextState: FSMState.AWAITING_ROUTING_ALTERNATIVE,
    };
  }

  // Shouldn't reach here, but handle gracefully
  return {
    response: `Something went wrong. Please try again.`,
    nextState: FSMState.ERROR,
  };
}
